import Head from "next/head";
import { useWeather } from "../hooks/useWeather";

export default function Home() {
  const { data, hours } = useWeather();
  const currentday = data?.list
 
  return (
    <>
      <Head>
        <title>Weather app</title>
        <meta name="description" content="Generated by Weather app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <p>{hours}</p>
        </div>
      </div>
    </>
  );
}
